name: dev
channels:
  - conda-forge
  - microsoft
  - pytorch
dependencies:
  # GENERAL -------------------------------------------------------------------
  # https://anaconda.org/conda-forge/pip
  - conda-forge::pip
  # https://anaconda.org/conda-forge/python
  - conda-forge::python
  # https://anaconda.org/conda-forge/nodejs
  - conda-forge::nodejs
  # TECHNICAL WRITING ---------------------------------------------------------
  # https://anaconda.org/conda-forge/markdown
  - conda-forge::markdown
  # https://anaconda.org/conda-forge/docutils
  - conda-forge::docutils
  # https://anaconda.org/conda-forge/sphinx
  - conda-forge::sphinx
  # https://anaconda.org/conda-forge/myst-parser
  - conda-forge::myst-parser
  # PYTHON --------------------------------------------------------------------
  # https://anaconda.org/conda-forge/pylint
  - conda-forge::pylint
  # https://anaconda.org/conda-forge/ipython
  - conda-forge::ipython
  # https://anaconda.org/conda-forge/jupyter
  - conda-forge::jupyter
  # https://anaconda.org/conda-forge/pytest
  - conda-forge::pytest
  # https://anaconda.org/conda-forge/pendulum
  - conda-forge::pendulum
  # https://anaconda.org/conda-forge/urllib3
  - conda-forge::urllib3
  # https://anaconda.org/conda-forge/tqdm
  - conda-forge::tqdm
  # DATA ----------------------------------------------------------------------
  # https://anaconda.org/conda-forge/numpy
  - conda-forge::numpy
  # https://anaconda.org/conda-forge/openpyxl
  - conda-forge::openpyxl
  # https://anaconda.org/conda-forge/pandas
  - conda-forge::pandas
  # https://anaconda.org/conda-forge/scipy
  - conda-forge::scipy
  # https://anaconda.org/conda-forge/pillow
  - conda-forge::pillow
  # WEB SCRAPING --------------------------------------------------------------
  # https://anaconda.org/conda-forge/requests
  - conda-forge::requests
  # https://anaconda.org/conda-forge/pysftp
  - conda-forge::pysftp
  # https://anaconda.org/conda-forge/lxml
  - conda-forge::lxml
  # https://anaconda.org/conda-forge/beautifulsoup4
  - conda-forge::beautifulsoup4
  # https://anaconda.org/conda-forge/selenium
  - conda-forge::selenium
  # https://anaconda.org/microsoft/playwright
  - microsoft::playwright
  # https://anaconda.org/conda-forge/twisted
  - conda-forge::twisted
  # https://anaconda.org/conda-forge/tornado
  - conda-forge::tornado
  # https://anaconda.org/conda-forge/scrapy
  - conda-forge::scrapy
  # VISUALIZATION -------------------------------------------------------------
  # https://anaconda.org/conda-forge/matplotlib
  - conda-forge::matplotlib
  # https://anaconda.org/conda-forge/seaborn
  - conda-forge::seaborn
  # https://anaconda.org/conda-forge/plotly
  - conda-forge::plotly
  # https://anaconda.org/conda-forge/dash
  - conda-forge::dash
  # https://anaconda.org/conda-forge/dash-core-components
  - conda-forge::dash-core-components
  # https://anaconda.org/conda-forge/dash-html-components
  - conda-forge::dash-html-components
  # https://anaconda.org/conda-forge/dash-bootstrap-components
  - conda-forge::dash-bootstrap-components
  # GUI -----------------------------------------------------------------------
  # https://anaconda.org/conda-forge/tk
  - conda-forge::tk
  # https://anaconda.org/conda-forge/pyqt
  - conda-forge::pyqt
  # https://anaconda.org/conda-forge/kivy
  - conda-forge::kivy
  # MACHINE LEARNING ----------------------------------------------------------
  # https://anaconda.org/conda-forge/scikit-learn
  - conda-forge::scikit-learn
  # https://anaconda.org/conda-forge/tensorflow
  - conda-forge::tensorflow
  # https://anaconda.org/pytorch/pytorch
  - pytorch::pytorch
  # https://anaconda.org/conda-forge/keras
  - conda-forge::keras
  # https://anaconda.org/conda-forge/nltk
  - conda-forge::nltk
  # https://anaconda.org/conda-forge/xgboost
  - conda-forge::xgboost
  # https://anaconda.org/conda-forge/catboost
  - conda-forge::catboost
  # WEB DEVELOPMENT -----------------------------------------------------------
  # https://anaconda.org/conda-forge/psycopg
  - conda-forge::psycopg
  # https://anaconda.org/conda-forge/psycopg2
  - conda-forge::psycopg2
  # https://anaconda.org/conda-forge/sqlalchemy
  - conda-forge::sqlalchemy
  # https://anaconda.org/conda-forge/jinja2
  - conda-forge::jinja2
  # https://anaconda.org/conda-forge/flask
  - conda-forge::flask
  # https://anaconda.org/conda-forge/fastapi
  - conda-forge::fastapi
  # https://anaconda.org/conda-forge/django
  - conda-forge::django
  # https://anaconda.org/conda-forge/django-extensions
  - conda-forge::django-extensions
  # https://anaconda.org/conda-forge/django-model-utils
  - conda-forge::django-model-utils
  # https://anaconda.org/conda-forge/django-import-export
  - conda-forge::django-import-export
  # https://anaconda.org/conda-forge/django-filter
  - conda-forge::django-filter
  # https://anaconda.org/conda-forge/django-debug-toolbar
  - conda-forge::django-debug-toolbar
  # https://anaconda.org/conda-forge/django-allauth
  - conda-forge::django-allauth
  # https://anaconda.org/conda-forge/django-storages
  - conda-forge::django-storages
  # https://anaconda.org/conda-forge/django-environ
  - conda-forge::django-environ
  # https://anaconda.org/conda-forge/django-crispy-forms
  - conda-forge::django-crispy-forms
  # https://anaconda.org/conda-forge/djangorestframework
  - conda-forge::djangorestframework
  # https://anaconda.org/conda-forge/django-cors-headers
  - conda-forge::django-cors-headers
  # https://anaconda.org/conda-forge/django-rest-auth
  - conda-forge::django-rest-auth
  # https://anaconda.org/conda-forge/djangorestframework_simplejwt
  - conda-forge::djangorestframework_simplejwt
  # https://anaconda.org/conda-forge/pytest-django
  - conda-forge::pytest-django
  # https://anaconda.org/conda-forge/pylint-django
  - conda-forge::pylint-django
  # https://anaconda.org/conda-forge/gunicorn
  - conda-forge::gunicorn
  # https://anaconda.org/conda-forge/uvicorn
  - conda-forge::uvicorn
  # https://anaconda.org/conda-forge/celery
  - conda-forge::celery
  # https://anaconda.org/conda-forge/flower
  - conda-forge::flower
  # https://anaconda.org/conda-forge/sentry-sdk
  - conda-forge::sentry-sdk
  # BIOINFORMATICS ------------------------------------------------------------
  # https://anaconda.org/conda-forge/biopython
  - conda-forge::biopython
  # https://anaconda.org/conda-forge/ete3
  - conda-forge::ete3
